# Generated by Django 4.1.1 on 2022-09-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
